WIP: update to socket.io v4
sockethub/sockethub pull request #371
Opened 2021-04-21 16:23 UTC by silverbucket

2021-04-22 15:59 UTC, silverbucket commented
@galfert @raucao tests passing, ready for review

2021-05-02 18:50 UTC, galfert requested changes
The code itself looks ok to me. But when testing with Hyperchannel, I get a 404 for http://localhost:10550/socket.io.js. In the Sockethub logs I see this error:

> Error: ENOENT: no such file or directory, stat '[...]/sockethub/packages/sockethub/node_modules/socket.io-client/dist/socket.io.js'

2021-05-02 18:50 UTC, galfert commented on packages/sockethub/src/sockethub.ts
> +    janitor.start(); // start cleanup cycle
Wouldn't `janitor.clean()` be an even better name?

2021-05-06 14:55 UTC, galfert approved these changes
There is still an open question from my first review. Other than that everything looks and works ok now.

2021-05-06 15:13 UTC, silverbucket commented
@galfert yeah I will make that change and then merge.

2021-05-06 15:13 UTC, silverbucket commented on packages/sockethub/src/sockethub.ts
> +    janitor.start(); // start cleanup cycle
Agreed, it's more thematic! :)

2021-05-06 15:32 UTC, merged